#!/bin/bash
#

# push manifest
if [[ ! -d $HOME/.docker ]]
then
    mkdir $HOME/.docker
fi

set -ex

if test $(uname) = "Linux"
then
	sed -i '/experimental/d' $HOME/.docker/config.json
	sed -i '1a"experimental": "enabled",' $HOME/.docker/config.json
fi

docker manifest create 457452950/static-server \
  457452950/static-server:latest \
  457452950/static-server:armhf
docker manifest annotate 457452950/static-server \
  457452950/static-server:latest --os linux --arch amd64
docker manifest annotate 457452950/static-server \
  457452950/static-server:armhf --os linux --arch arm --variant v7
docker manifest push 457452950/static-server

# check again
docker run mplatform/mquery 457452950/static-server
